# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Showerbugs
paginate:       5
baseurl:        ""
url:            "https://showerbugs.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
authors:
  hou:
    name: Min-Ho Choi
    nickname: hou
    image: 'assets/images/minho.jpg'
    bio: 'Front 개발자 입니다.'
    location: Suwon, Korea
    email: vnthf1@naver.com
    github: Vnthf
    url: https://vnthf.logdown.com
  qodot:
    name: Dae-Won Seo
    nickname: qodot
    image: assets/images/qodot.png
    bio: Python을 좋아하는 서버 개발자입니다.
    location: Seoul, Korea
    email: waitingforqodot@gmail.com
    github: qodot
    url: https://qodot.github.io
  aiden:
    name: Dae-Yoon Kim
    nickname: Aiden
    image: assets/images/kdaeyoon88.png
    bio: Android 개발자입니다;
    location: Suwon, Korea
    email: kdaeyoon88@gmail.com
    github: kdaeyoon88
    url: https://kdaeyoon88.github.io

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate

google_analytics: UA-99504405-1
disqus: showerbugs