# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Showerbugs
paginate:       5
baseurl:        ""
url:            "https://showerbugs.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed
collections:
  books:
    output: true

# Build settings
markdown:       kramdown

# About
authors:
  hou:
    name: Min-Ho Choi
    nickname: hou
    image: assets/images/minho.jpg
    bio: 풀스택을 지향하는 프론트 개발자 입니다.
    location: Suwon, Korea
    email: vnthf1@naver.com
    github: Vnthf
    url: http://vnthf.logdown.com
  qodot:
    name: Dae-Won Seo
    nickname: qodot
    image: assets/images/qodot.png
    bio: Python을 좋아하는 서버 개발자입니다.
    location: Seoul, Korea
    email: waitingforqodot@gmail.com
    github: qodot
    url: https://qodot.github.io
  aiden:
    name: Dae-Yoon Kim
    nickname: Aiden
    image: assets/images/kdaeyoon88.jpg
    bio: Android 개발자입니다.
    location: Suwon, Korea
    email: kdaeyoon88@gmail.com
    github: kdaeyoon88
    url: https://kdaeyoon88.github.io
  amazingguni:
    name: Young-Gun Na
    nickname: guni
    image: assets/images/amazingguni.jpg
    bio: 소프트웨어 장인으로의 길을 찾기 위해 넓고 얕은 지식을 쌓고 있는 평범한 개발자입니다.
    location: Suwon, Korea
    email: amazingguni@gmail.com
    github: amazingguni
    url: https://amazingguni.github.io

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# plugins
plugins:
  - jekyll-paginate

google_analytics: UA-99504405-1
disqus: showerbugs
